import React, { useState } from 'react';
import axios from 'axios';
import { NIMRecord } from '../interfaces/NIMRecord';

function AddNIM() {
    const [newNim, setNewNim] = useState<NIMRecord>({
        NIM_ID: 0, // This will be auto-generated by the database
        Model: '',
        Temperature: '',
        Top_P: '',
        Max_Tokens: 1024,
        Stream: false,
        Name: '',
    });

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setNewNim({ ...newNim, [event.target.name]: event.target.value });
    };

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
    
        // Destructure newNim to exclude NIM_ID and capture the rest of the properties
        const { NIM_ID, ...payload } = newNim;
    
        try {
            // Specify the content type as JSON and send the payload
            const response = await axios.post('/api/create_nim', payload, {
                headers: {
                    'Content-Type': 'application/json',
                },
            });
            console.log('NIM created:', response.data);
    
            // Redirect to the home page after successful creation
            window.location.href = '/';
        } catch (error) {
            // Log the data to the console if there's an error
            console.log('Error creating NIM:', payload);
            console.error('Error creating NIM:', error);
        }
    };
    

    return (
        <div>
        <h2>Add NIM</h2>
        <form onSubmit={handleSubmit}>
            <div>
            <label htmlFor="Name">Name:</label>
                <input
                    type="text"
                    id="Name"
                    name="Name"
                    value={newNim.Name}
                    onChange={handleChange}
                    required
                />
            </div>
            <div>
            <label htmlFor="Model">Model:</label>
                <input
                    type="text"
                    id="Model"
                    name="Model"
                    value={newNim.Model}
                    onChange={handleChange}
                    required
                />
            </div>
            <div>
            <label htmlFor="Temperature">Temperature:</label>
                <input
                    type="number"
                    id="Temperature"
                    name="Temperature"
                    value={newNim.Temperature}
                    onChange={handleChange}
                />
            </div>
            <div>
            <label htmlFor="Top_P">Top_P:</label>
                <input
                    type="number"
                    id="Top_P"
                    name="Top_P"
                    value={newNim.Top_P}
                    onChange={handleChange}
                />
            </div>
            <div>
            <label htmlFor="Max_Tokens">Max_Tokens:</label>
                <input
                    type="number"
                    id="Max_Tokens"
                    name="Max_Tokens"
                    value={newNim.Max_Tokens}
                    onChange={handleChange}
                />
            </div>

            <button type="submit">Create NIM</button>
        </form>
        </div>
    );
}

export default AddNIM;