import React, { useState } from 'react';
import axios from 'axios';
import { NIMRecord } from '../interfaces/NIMRecord';

function AddNIM() {
    const [newNim, setNewNim] = useState<NIMRecord>({
        NIM_ID: 0, // This will be auto-generated by the database
        Model: '',
        Temperature: '',
        Top_P: '',
        Max_Tokens: 1024,
        Stream: false,
        Name: '',
    });

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setNewNim({ ...newNim, [event.target.name]: event.target.value });
    };

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();

        try {
        const response = await axios.post('/api/nims', newNim);
        console.log('NIM created:', response.data);
        // Clear the form after successful creation
        setNewNim({
            NIM_ID: 0,
            Model: '',
            Temperature: '',
            Top_P: '',
            Max_Tokens: 1024,
            Stream: false,
            Name: '',
        });
        // You might want to redirect to the home page or display a success message here
        } catch (error) {
        console.error('Error creating NIM:', error);
        // Handle the error appropriately, e.g., display an error message to the user
        }
    };

    return (
        <div>
        <h2>Add NIM</h2>
        <form onSubmit={handleSubmit}>
            <div>
            <label htmlFor="Name">Name:</label>
                <input
                    type="text"
                    id="Name"
                    name="Name"
                    value={newNim.Name}
                    onChange={handleChange}
                    required
                />
            </div>
            <div>
            <label htmlFor="Model">Model:</label>
                <input
                    type="text"
                    id="Model"
                    name="Model"
                    value={newNim.Model}
                    onChange={handleChange}
                    required
                />
            </div>


            <button type="submit">Create NIM</button>
        </form>
        </div>
    );
}

export default AddNIM;